#!/usr/bin/env python3
"""
Improved test script with realistic network traffic data patterns
Based on actual CICIDS attack characteristics
"""
import json
import time
from kafka import KafkaProducer

# Load realistic test data (generated by debug script)
def load_realistic_data():
    """Load realistic data or create it if not available"""
    try:
        with open('realistic_test_data.json', 'r') as f:
            return json.load(f)
    except FileNotFoundError:
        # Fallback to hardcoded realistic data
        return create_hardcoded_realistic_data()

def create_hardcoded_realistic_data():
    """Create hardcoded realistic attack patterns"""
    
    # DDoS SYN Flood pattern (high packet rate, no responses)
    ddos_syn_flood = {
        "Destination Port": 80,
        "Flow Duration": 500000,  # 0.5 seconds
        "Total Fwd Packets": 10000,  # Very high
        "Total Backward Packets": 0,  # No responses
        "Total Length of Fwd Packets": 640000,  # Small SYN packets
        "Total Length of Bwd Packets": 0,
        "Fwd Packet Length Max": 64,
        "Fwd Packet Length Min": 64,
        "Fwd Packet Length Mean": 64,
        "Fwd Packet Length Std": 0,
        "Bwd Packet Length Max": 0,
        "Bwd Packet Length Min": 0,
        "Bwd Packet Length Mean": 0,
        "Bwd Packet Length Std": 0,
        "Flow Bytes/s": 1280000,  # Very high rate
        "Flow Packets/s": 20000,  # Very high packet rate
        "Flow IAT Mean": 50,      # Very small inter-arrival time
        "Flow IAT Std": 10,
        "Flow IAT Max": 100,
        "Flow IAT Min": 10,
        "Fwd IAT Total": 499950,
        "Fwd IAT Mean": 49.995,
        "Fwd IAT Std": 10,
        "Fwd IAT Max": 100,
        "Fwd IAT Min": 10,
        "Bwd IAT Total": 0,
        "Bwd IAT Mean": 0,
        "Bwd IAT Std": 0,
        "Bwd IAT Max": 0,
        "Bwd IAT Min": 0,
        "Fwd PSH Flags": 0,  # SYN flood has no PSH
        "Fwd URG Flags": 0,
        "Fwd Header Length": 400000,  # Only headers, no data
        "Bwd Header Length": 0,
        "Fwd Packets/s": 20000,
        "Bwd Packets/s": 0,
        "Min Packet Length": 64,
        "Max Packet Length": 64,
        "Packet Length Mean": 64,
        "Packet Length Std": 0,
        "Packet Length Variance": 0,
        "FIN Flag Count": 0,
        "RST Flag Count": 0,
        "PSH Flag Count": 0,
        "ACK Flag Count": 0,
        "URG Flag Count": 0,
        "ECE Flag Count": 0,
        "Down/Up Ratio": 0,  # No downstream packets
        "Average Packet Size": 64,
        "Avg Fwd Segment Size": 64,
        "Avg Bwd Segment Size": 0,
        "Subflow Fwd Bytes": 640000,
        "Subflow Bwd Bytes": 0,
        "Init_Win_bytes_forward": 0,  # SYN flood may not establish proper windows
        "Init_Win_bytes_backward": 0,
        "act_data_pkt_fwd": 0,  # No actual data packets
        "min_seg_size_forward": 64,
        "Active Mean": 500000,
        "Active Std": 0,
        "Active Max": 500000,
        "Active Min": 500000,
        "Idle Mean": 0,
        "Idle Std": 0,
        "Idle Max": 0,
        "Idle Min": 0,
        "profile": "ddos"
    }
    
    # PortScan pattern (many different ports, small packets)
    portscan = {
        "Destination Port": 22,  # SSH port being scanned
        "Flow Duration": 100000,  # 0.1 seconds
        "Total Fwd Packets": 1,   # Single probe packet
        "Total Backward Packets": 0,  # Often no response or RST
        "Total Length of Fwd Packets": 64,
        "Total Length of Bwd Packets": 0,
        "Fwd Packet Length Max": 64,
        "Fwd Packet Length Min": 64,
        "Fwd Packet Length Mean": 64,
        "Fwd Packet Length Std": 0,
        "Bwd Packet Length Max": 0,
        "Bwd Packet Length Min": 0,
        "Bwd Packet Length Mean": 0,
        "Bwd Packet Length Std": 0,
        "Flow Bytes/s": 640,
        "Flow Packets/s": 10,
        "Flow IAT Mean": 0,  # Single packet
        "Flow IAT Std": 0,
        "Flow IAT Max": 0,
        "Flow IAT Min": 0,
        "Fwd IAT Total": 0,
        "Fwd IAT Mean": 0,
        "Fwd IAT Std": 0,
        "Fwd IAT Max": 0,
        "Fwd IAT Min": 0,
        "Bwd IAT Total": 0,
        "Bwd IAT Mean": 0,
        "Bwd IAT Std": 0,
        "Bwd IAT Max": 0,
        "Bwd IAT Min": 0,
        "Fwd PSH Flags": 0,
        "Fwd URG Flags": 0,
        "Fwd Header Length": 40,
        "Bwd Header Length": 0,
        "Fwd Packets/s": 10,
        "Bwd Packets/s": 0,
        "Min Packet Length": 64,
        "Max Packet Length": 64,
        "Packet Length Mean": 64,
        "Packet Length Std": 0,
        "Packet Length Variance": 0,
        "FIN Flag Count": 0,
        "RST Flag Count": 0,
        "PSH Flag Count": 0,
        "ACK Flag Count": 0,
        "URG Flag Count": 0,
        "ECE Flag Count": 0,
        "Down/Up Ratio": 0,
        "Average Packet Size": 64,
        "Avg Fwd Segment Size": 64,
        "Avg Bwd Segment Size": 0,
        "Subflow Fwd Bytes": 64,
        "Subflow Bwd Bytes": 0,
        "Init_Win_bytes_forward": 0,
        "Init_Win_bytes_backward": 0,
        "act_data_pkt_fwd": 0,
        "min_seg_size_forward": 64,
        "Active Mean": 100000,
        "Active Std": 0,
        "Active Max": 100000,
        "Active Min": 100000,
        "Idle Mean": 0,
        "Idle Std": 0,
        "Idle Max": 0,
        "Idle Min": 0,
        "profile": "portscan"
    }
    
    # Botnet communication pattern (periodic, encrypted)
    botnet = {
        "Destination Port": 443,  # HTTPS to mask communication
        "Flow Duration": 10000000,  # 10 seconds
        "Total Fwd Packets": 50,
        "Total Backward Packets": 48,
        "Total Length of Fwd Packets": 2500,  # Small command packets
        "Total Length of Bwd Packets": 72000,  # Larger response data
        "Fwd Packet Length Max": 80,
        "Fwd Packet Length Min": 40,
        "Fwd Packet Length Mean": 50,
        "Fwd Packet Length Std": 15,
        "Bwd Packet Length Max": 1500,
        "Bwd Packet Length Min": 1500,
        "Bwd Packet Length Mean": 1500,
        "Bwd Packet Length Std": 0,  # Very consistent packet sizes
        "Flow Bytes/s": 7450,
        "Flow Packets/s": 9.8,
        "Flow IAT Mean": 204081.63,  # Regular intervals
        "Flow IAT Std": 5000,  # Very low variation (periodic)
        "Flow IAT Max": 220000,
        "Flow IAT Min": 190000,
        "Fwd IAT Total": 9800000,
        "Fwd IAT Mean": 200000,  # Very regular
        "Fwd IAT Std": 2000,
        "Fwd IAT Max": 205000,
        "Fwd IAT Min": 195000,
        "Bwd IAT Total": 9600000,
        "Bwd IAT Mean": 204255.32,
        "Bwd IAT Std": 2000,
        "Bwd IAT Max": 208000,
        "Bwd IAT Min": 200000,
        "Fwd PSH Flags": 25,  # Half the packets push data
        "Fwd URG Flags": 0,
        "Fwd Header Length": 2000,
        "Bwd Header Length": 1920,
        "Fwd Packets/s": 5.0,
        "Bwd Packets/s": 4.8,
        "Min Packet Length": 40,
        "Max Packet Length": 1500,
        "Packet Length Mean": 760.2,
        "Packet Length Std": 725,
        "Packet Length Variance": 525625,
        "FIN Flag Count": 2,
        "RST Flag Count": 0,
        "PSH Flag Count": 35,
        "ACK Flag Count": 90,
        "URG Flag Count": 0,
        "ECE Flag Count": 0,
        "Down/Up Ratio": 0.96,
        "Average Packet Size": 760.2,
        "Avg Fwd Segment Size": 50,
        "Avg Bwd Segment Size": 1500,
        "Subflow Fwd Bytes": 2500,
        "Subflow Bwd Bytes": 72000,
        "Init_Win_bytes_forward": 65535,
        "Init_Win_bytes_backward": 65535,
        "act_data_pkt_fwd": 40,
        "min_seg_size_forward": 40,
        "Active Mean": 7000000,
        "Active Std": 500000,
        "Active Max": 7500000,
        "Active Min": 6500000,
        "Idle Mean": 1500000,
        "Idle Std": 100000,
        "Idle Max": 1600000,
        "Idle Min": 1400000,
        "profile": "botnet"
    }
    
    # Normal web browsing
    normal_web = {
        "Destination Port": 443,
        "Flow Duration": 5000000,  # 5 seconds
        "Total Fwd Packets": 25,
        "Total Backward Packets": 23,
        "Total Length of Fwd Packets": 4000,
        "Total Length of Bwd Packets": 34500,
        "Fwd Packet Length Max": 200,
        "Fwd Packet Length Min": 40,
        "Fwd Packet Length Mean": 160,
        "Fwd Packet Length Std": 40,
        "Bwd Packet Length Max": 1500,
        "Bwd Packet Length Min": 1400,
        "Bwd Packet Length Mean": 1500,
        "Bwd Packet Length Std": 25,
        "Flow Bytes/s": 7700,
        "Flow Packets/s": 9.6,
        "Flow IAT Mean": 106382.98,
        "Flow IAT Std": 80000,
        "Flow IAT Max": 300000,
        "Flow IAT Min": 10000,
        "Fwd IAT Total": 4800000,
        "Fwd IAT Mean": 200000,
        "Fwd IAT Std": 100000,
        "Fwd IAT Max": 400000,
        "Fwd IAT Min": 50000,
        "Bwd IAT Total": 4600000,
        "Bwd IAT Mean": 209090.91,
        "Bwd IAT Std": 90000,
        "Bwd IAT Max": 380000,
        "Bwd IAT Min": 60000,
        "Fwd PSH Flags": 3,
        "Fwd URG Flags": 0,
        "Fwd Header Length": 1000,
        "Bwd Header Length": 920,
        "Fwd Packets/s": 5.0,
        "Bwd Packets/s": 4.6,
        "Min Packet Length": 40,
        "Max Packet Length": 1500,
        "Packet Length Mean": 802.1,
        "Packet Length Std": 650,
        "Packet Length Variance": 422500,
        "FIN Flag Count": 2,
        "RST Flag Count": 0,
        "PSH Flag Count": 8,
        "ACK Flag Count": 44,
        "URG Flag Count": 0,
        "ECE Flag Count": 0,
        "Down/Up Ratio": 0.92,
        "Average Packet Size": 802.1,
        "Avg Fwd Segment Size": 160,
        "Avg Bwd Segment Size": 1500,
        "Subflow Fwd Bytes": 4000,
        "Subflow Bwd Bytes": 34500,
        "Init_Win_bytes_forward": 65535,
        "Init_Win_bytes_backward": 65535,
        "act_data_pkt_fwd": 20,
        "min_seg_size_forward": 40,
        "Active Mean": 3500000,
        "Active Std": 400000,
        "Active Max": 4000000,
        "Active Min": 3000000,
        "Idle Mean": 750000,
        "Idle Std": 150000,
        "Idle Max": 900000,
        "Idle Min": 600000,
        "profile": "normal"
    }
    
    # DoS HTTP Flood (different from DDoS)
    dos_http_flood = {
        "Destination Port": 80,
        "Flow Duration": 2000000,  # 2 seconds
        "Total Fwd Packets": 2000,  # High but not as extreme as DDoS
        "Total Backward Packets": 1,  # Single error response
        "Total Length of Fwd Packets": 160000,  # Larger HTTP requests
        "Total Length of Bwd Packets": 500,  # Error page
        "Fwd Packet Length Max": 1024,
        "Fwd Packet Length Min": 60,
        "Fwd Packet Length Mean": 80,
        "Fwd Packet Length Std": 20,
        "Bwd Packet Length Max": 500,
        "Bwd Packet Length Min": 500,
        "Bwd Packet Length Mean": 500,
        "Bwd Packet Length Std": 0,
        "Flow Bytes/s": 80250,
        "Flow Packets/s": 1000.5,
        "Flow IAT Mean": 999.5,
        "Flow IAT Std": 200,
        "Flow IAT Max": 1500,
        "Flow IAT Min": 500,
        "Fwd IAT Total": 1998000,
        "Fwd IAT Mean": 999,
        "Fwd IAT Std": 200,
        "Fwd IAT Max": 1400,
        "Fwd IAT Min": 600,
        "Bwd IAT Total": 0,
        "Bwd IAT Mean": 0,
        "Bwd IAT Std": 0,
        "Bwd IAT Max": 0,
        "Bwd IAT Min": 0,
        "Fwd PSH Flags": 2000,  # All HTTP requests have PSH
        "Fwd URG Flags": 0,
        "Fwd Header Length": 80000,
        "Bwd Header Length": 40,
        "Fwd Packets/s": 1000,
        "Bwd Packets/s": 0.5,
        "Min Packet Length": 60,
        "Max Packet Length": 1024,
        "Packet Length Mean": 80.2,
        "Packet Length Std": 20,
        "Packet Length Variance": 400,
        "FIN Flag Count": 1,
        "RST Flag Count": 1,
        "PSH Flag Count": 2000,
        "ACK Flag Count": 2001,
        "URG Flag Count": 0,
        "ECE Flag Count": 0,
        "Down/Up Ratio": 0.0005,
        "Average Packet Size": 80.2,
        "Avg Fwd Segment Size": 80,
        "Avg Bwd Segment Size": 500,
        "Subflow Fwd Bytes": 160000,
        "Subflow Bwd Bytes": 500,
        "Init_Win_bytes_forward": 65535,
        "Init_Win_bytes_backward": 0,
        "act_data_pkt_fwd": 2000,
        "min_seg_size_forward": 60,
        "Active Mean": 2000000,
        "Active Std": 0,
        "Active Max": 2000000,
        "Active Min": 2000000,
        "Idle Mean": 0,
        "Idle Std": 0,
        "Idle Max": 0,
        "Idle Min": 0,
        "profile": "dos"
    }
    
    return [normal_web, ddos_syn_flood, portscan, botnet, dos_http_flood]

def send_test_data():
    """Send more realistic attack patterns to Kafka"""
    producer = KafkaProducer(
        bootstrap_servers=['127.0.0.1:9092'],
        value_serializer=lambda v: json.dumps(v).encode('utf-8'),
        retries=5
    )
    
    print("Sending realistic network traffic data to Kafka...")
    
    # Load or create realistic data
    test_data = load_realistic_data()
    
    for i, record in enumerate(test_data):
        try:
            profile = record.get('profile', 'unknown')
            dest_port = record.get('Destination Port', 'unknown')
            packet_rate = record.get('Flow Packets/s', 0)
            
            producer.send('network-traffic', record)
            print(f"Sent record {i+1}: {profile} traffic to port {dest_port} (rate: {packet_rate:.1f} pkt/s)")
            time.sleep(3)  # Send one record every 3 seconds
            
        except Exception as e:
            print(f"Error sending record: {e}")
    
    # Send a few more varied samples
    print("\nSending additional attack variations...")
    
    # High-rate UDP flood
    udp_flood = {
        "Destination Port": 53,  # DNS
        "Flow Duration": 200000,  # 0.2 seconds
        "Total Fwd Packets": 8000,
        "Total Backward Packets": 0,
        "Total Length of Fwd Packets": 512000,  # 64 bytes each
        "Total Length of Bwd Packets": 0,
        "Fwd Packet Length Max": 64,
        "Fwd Packet Length Min": 64,
        "Fwd Packet Length Mean": 64,
        "Fwd Packet Length Std": 0,
        "Bwd Packet Length Max": 0,
        "Bwd Packet Length Min": 0,
        "Bwd Packet Length Mean": 0,
        "Bwd Packet Length Std": 0,
        "Flow Bytes/s": 2560000,  # Very high
        "Flow Packets/s": 40000,   # Extremely high
        "Flow IAT Mean": 25,       # Very small
        "Flow IAT Std": 5,
        "Flow IAT Max": 35,
        "Flow IAT Min": 15,
        "Fwd IAT Total": 199975,
        "Fwd IAT Mean": 24.997,
        "Fwd IAT Std": 5,
        "Fwd IAT Max": 35,
        "Fwd IAT Min": 15,
        "Bwd IAT Total": 0,
        "Bwd IAT Mean": 0,
        "Bwd IAT Std": 0,
        "Bwd IAT Max": 0,
        "Bwd IAT Min": 0,
        "Fwd PSH Flags": 0,
        "Fwd URG Flags": 0,
        "Fwd Header Length": 320000,
        "Bwd Header Length": 0,
        "Fwd Packets/s": 40000,
        "Bwd Packets/s": 0,
        "Min Packet Length": 64,
        "Max Packet Length": 64,
        "Packet Length Mean": 64,
        "Packet Length Std": 0,
        "Packet Length Variance": 0,
        "Average Packet Size": 64,
        "Avg Fwd Segment Size": 64,
        "Avg Bwd Segment Size": 0,
        "Subflow Fwd Bytes": 512000,
        "Subflow Bwd Bytes": 0,
        "Init_Win_bytes_forward": 0,
        "Init_Win_bytes_backward": 0,
        "act_data_pkt_fwd": 8000,
        "min_seg_size_forward": 64,
        "Active Mean": 200000,
        "Active Std": 0,
        "Active Max": 200000,
        "Active Min": 200000,
        "Idle Mean": 0,
        "Idle Std": 0,
        "Idle Max": 0,
        "Idle Min": 0,
        "Down/Up Ratio": 0,
        "FIN Flag Count": 0,
        "RST Flag Count": 0,
        "PSH Flag Count": 0,
        "ACK Flag Count": 0,
        "URG Flag Count": 0,
        "ECE Flag Count": 0,
        "profile": "udp_flood"
    }
    
    # Web attack (SQLi attempt)
    web_attack = {
        "Destination Port": 80,
        "Flow Duration": 1000000,  # 1 second
        "Total Fwd Packets": 1,    # Single malicious request
        "Total Backward Packets": 1,  # Error response
        "Total Length of Fwd Packets": 2048,  # Large SQL payload
        "Total Length of Bwd Packets": 500,   # Error page
        "Fwd Packet Length Max": 2048,
        "Fwd Packet Length Min": 2048,
        "Fwd Packet Length Mean": 2048,
        "Fwd Packet Length Std": 0,
        "Bwd Packet Length Max": 500,
        "Bwd Packet Length Min": 500,
        "Bwd Packet Length Mean": 500,
        "Bwd Packet Length Std": 0,
        "Flow Bytes/s": 2548,
        "Flow Packets/s": 2,
        "Flow IAT Mean": 0,
        "Flow IAT Std": 0,
        "Flow IAT Max": 0,
        "Flow IAT Min": 0,
        "Fwd IAT Total": 0,
        "Fwd IAT Mean": 0,
        "Fwd IAT Std": 0,
        "Fwd IAT Max": 0,
        "Fwd IAT Min": 0,
        "Bwd IAT Total": 0,
        "Bwd IAT Mean": 0,
        "Bwd IAT Std": 0,
        "Bwd IAT Max": 0,
        "Bwd IAT Min": 0,
        "Fwd PSH Flags": 1,
        "Fwd URG Flags": 0,
        "Fwd Header Length": 40,
        "Bwd Header Length": 40,
        "Fwd Packets/s": 1,
        "Bwd Packets/s": 1,
        "Min Packet Length": 500,
        "Max Packet Length": 2048,
        "Packet Length Mean": 1274,
        "Packet Length Std": 774,
        "Packet Length Variance": 599076,
        "Average Packet Size": 1274,
        "Avg Fwd Segment Size": 2048,
        "Avg Bwd Segment Size": 500,
        "Subflow Fwd Bytes": 2048,
        "Subflow Bwd Bytes": 500,
        "Init_Win_bytes_forward": 65535,
        "Init_Win_bytes_backward": 65535,
        "act_data_pkt_fwd": 1,
        "min_seg_size_forward": 2048,
        "Active Mean": 1000000,
        "Active Std": 0,
        "Active Max": 1000000,
        "Active Min": 1000000,
        "Idle Mean": 0,
        "Idle Std": 0,
        "Idle Max": 0,
        "Idle Min": 0,
        "Down/Up Ratio": 1,
        "FIN Flag Count": 2,
        "RST Flag Count": 0,
        "PSH Flag Count": 2,
        "ACK Flag Count": 2,
        "URG Flag Count": 0,
        "ECE Flag Count": 0,
        "profile": "web_attack"
    }
    
    additional_samples = [udp_flood, web_attack]
    
    for i, record in enumerate(additional_samples):
        try:
            profile = record.get('profile', 'unknown')
            producer.send('network-traffic', record)
            print(f"Sent additional sample {i+1}: {profile}")
            time.sleep(3)
        except Exception as e:
            print(f"Error sending additional record: {e}")
    
    producer.flush()
    producer.close()
    print("Realistic test data sent successfully!")

def main():
    """Main function with options"""
    import sys
    
    if len(sys.argv) > 1 and sys.argv[1] == "--create-debug-data":
        # Just create and save the realistic data
        realistic_data = create_hardcoded_realistic_data()
        with open('realistic_test_data.json', 'w') as f:
            json.dump(realistic_data, f, indent=2)
        print("Created realistic_test_data.json")
        return
    
    # Send data to Kafka
    send_test_data()

if __name__ == "__main__":
    main()